pr:
  branches:
    include:
      - main
    exclude:
      - "release/[0-4].x"
  paths:
    include:
      - scripts/azure_deployment/*
      - .azure_pipelines_snp.yml
      - .azure-pipelines-templates/deploy_aci.yml
      - .snpcc_canary

schedules:
  - cron: "0 0 * * *"
    displayName: Regular build
    branches:
      include:
        - main
    always: true

resources:
  containers:
    - container: virtual
      image: ccfmsrc.azurecr.io/ccf/ci:2024-06-26-virtual-clang15
      options: --publish-all --cap-add NET_ADMIN --cap-add NET_RAW --cap-add SYS_PTRACE -v /lib/modules:/lib/modules:ro

jobs:
  - template: .azure-pipelines-templates/deploy_aci.yml
